import { describe, expect, it, mock } from 'bun:test'

/**
 * These tests verify the SEO behavior of article pages by testing
 * that the meta tags generated by our composables produce correct outputs.
 * We test the composables directly (unit behavior) since mounting full Nuxt pages
 * is not feasible in unit tests.
 */

const mockUseRuntimeConfig = mock(() => ({
  public: { baseUrl: 'https://blog.hoppr.tech' },
}))

const mockUseHead = mock(() => {})

;(globalThis as any).useRuntimeConfig = mockUseRuntimeConfig
;(globalThis as any).useHead = mockUseHead

const { usePageSeo } = await import('@/composables/usePageSeo')
const { useAbsoluteUrl } = await import('@/composables/useAbsoluteUrl')

describe('article meta tags - og:image absolute URLs (TASK-004)', () => {
  it('should produce absolute og:image URL when article has a cover image', () => {
    // Given: an article with a cover image (relative path from resolveContentAsset)
    const coverImage = '/content-assets/2024-01-01-my-article/assets/cover.webp'

    // When: we generate SEO meta for the article
    usePageSeo({
      title: 'Mon Article',
      description: 'Description de test',
      url: '/blogs/2024-01-01-my-article',
      image: coverImage,
      type: 'article',
    })

    // Then: og:image starts with https://
    const call = mockUseHead.mock.lastCall![0]
    const ogImage = call.meta.find((m: any) => m.property === 'og:image')
    expect(ogImage.content).toMatch(/^https:\/\//)
    expect(ogImage.content).toBe('https://blog.hoppr.tech/content-assets/2024-01-01-my-article/assets/cover.webp')

    // And: twitter:image also starts with https://
    const twitterImage = call.meta.find((m: any) => m.name === 'twitter:image')
    expect(twitterImage.content).toMatch(/^https:\/\//)
  })

  it('should produce absolute image URL via useAbsoluteUrl for JSON-LD', () => {
    // Given: an article image path
    const imagePath = '/content-assets/slug/assets/cover.webp'

    // When: we convert it to absolute URL (used in JSON-LD generation)
    const absoluteImage = useAbsoluteUrl(imagePath)

    // Then: the JSON-LD image is absolute
    expect(absoluteImage).toMatch(/^https:\/\//)
    expect(absoluteImage).toBe('https://blog.hoppr.tech/content-assets/slug/assets/cover.webp')
  })
})

describe('article meta tags - og:type is "article" (TASK-006)', () => {
  it('should set og:type to "article" for blog posts', () => {
    // Given: an article page
    // When: we generate SEO meta with type "article"
    usePageSeo({
      title: 'Mon Article',
      description: 'Description',
      url: '/blogs/2024-01-01-my-article',
      type: 'article',
    })

    // Then: og:type = "article"
    const call = mockUseHead.mock.lastCall![0]
    const ogType = call.meta.find((m: any) => m.property === 'og:type')
    expect(ogType.content).toBe('article')
  })
})

describe('article meta tags - JSON-LD no double-slash (TASK-014)', () => {
  it('should not produce double-slash in mainEntityOfPage URL', () => {
    // Given: an article with path /blogs/my-article
    const baseUrl = 'https://blog.hoppr.tech'
    const articlePath = '/blogs/my-article'

    // When: we construct the mainEntityOfPage URL
    // The correct way: baseUrl + path (no extra /)
    const url = `${baseUrl}${articlePath}`

    // Then: no double-slash after domain
    expect(url).not.toMatch(/hoppr\.tech\/\//)
    expect(url).toBe('https://blog.hoppr.tech/blogs/my-article')
  })

  it('should not produce double-slash when using useAbsoluteUrl', () => {
    const url = useAbsoluteUrl('/blogs/my-article')
    expect(url).not.toMatch(/hoppr\.tech\/\//)
  })
})

describe('article meta tags - dates in time elements (TASK-033)', () => {
  it('should format date as ISO 8601 for datetime attribute', () => {
    // Given: an article date
    const date = '2024-06-10'

    // Then: the date can be used in a <time datetime> attribute (YYYY-MM-DD format)
    expect(date).toMatch(/^\d{4}-\d{2}-\d{2}/)
  })
})
