name: _billtest
on: workflow_dispatch
jobs:
  sh_min:
    runs-on: self-hosted
    steps:
      - run: echo "self-hosted (label minimal) OK"
  sh_full:
    runs-on: [self-hosted, linux, M]
    steps:
      - run: echo "self-hosted (self-hosted,linux,M) OK"
